### ISSUE TITLE
latest cht-conf fails to upgrade app settings to latest CHT endpoints

### ISSUE THREAD

**Issue by 1yuv** [medic/cht-conf#596] opened 2024-01-05 16:26 UTC
**Describe the bug**
cht-conf fails to upgrade valid app-setting to valid endpoint with following error:
```
INFO Starting action: upload-app-settings… 
INFO TypeError: Invalid Version: null
ERROR Invalid Version: null 
```

**To Reproduce**
1. Deploy 4.5.0 instance
2. Prepare valid app settings
3. Try to upload (`cht-conf upload-app-settings`) to instance on step 1 with cht-conf 3.19.0 or later

**Expected behavior**
We should be able to upload without any issue

**Logs**
If applicable, include the cht-conf output, server logs, and/or browser logs.

**Screenshots**

**Environment**
- Instance: gandaki.dev
- Client platform: (eg: Windows, MacOS, Linux)
- cht-conf version: 3.21.1
- cht-core version: 4.5.0

**Additional context**
This appears to be caused by [this feature](https://github.com/medic/cht-conf/issues/225), which was released on 3.19.0.

This [code](https://github.com/medic/cht-conf/blob/main/src/fn/upload-app-settings.js#L41) tries to extract latest api version, which is `4.5.0.6922454971` for 4.5.0 instances and semver considers it invalid version while comparing it with semver.

**Comment by 1yuv** [comment] 2024-01-05 18:27
This is critical for one of our deployment to have this fixed and deployed, so I'll be working on it.

**Comment by tatilepizs** [comment] 2024-01-10 19:21
I was trying to test this ticket but I was not able to reproduce the error in my local environment.
I followed the instructions added in the description of the ticket -> [here](https://github.com/medic/cht-conf/issues/596#issue-2067650308), and the upload is working every time.

I am using:
- cht-core version `4.5.0`

  ![image](https://github.com/medic/cht-conf/assets/94494491/62f03c24-2b04-4c49-b997-9b80987cd030)

- cht-conf version `3.21.1` (I also tried with version `3.20.0` and had the same result)

  ``` .bash
   ➜  ~ cht --version
   INFO 3.21.1
  ```

I tried these two configs:

[default config ](https://github.com/medic/cht-core/tree/master/config/default)

``` .bash
➜  default git:(4.5.x) ✗ cht --url=https://medic:******@127-0-0-1.local-ip.medicmobile.org:10446 upload-app-settings
INFO Checking that https://medic:****@127-0-0-1.local-ip.medicmobile.org:10446/medic/ is available...
INFO Processing config in default.
INFO Actions:
     - upload-app-settings
INFO Starting action: upload-app-settings…
WARN generate_patient_id_on_people transition is deprecated since 3.8.x. Please use "generate_shortcode_on_contacts" transition instead.
INFO Settings updated successfully
INFO upload-app-settings complete.
```

[gandaki-province](https://github.com/medic/config-moh-nepal/tree/master/gandaki-province) - (config suggested by Yuvraj

``` .bash
➜  gandaki-province git:(master) ✗ cht --url=https://medic:*****@127-0-0-1.local-ip.medicmobile.org:10446 upload-app-settings
INFO Checking that https://medic:****@127-0-0-1.local-ip.medicmobile.org:10446/medic/ is available...
INFO Processing config in gandaki-province.
INFO Actions:
     - upload-app-settings
INFO Starting action: upload-app-settings…
INFO Settings updated successfully
INFO upload-app-settings complete.
```

@1yuv Since this is an important ticket that needs to be released as soon as possible I think that it would be enough if you could add your testing showing the error and then how it was fixed using your branch ([596_semver_fix](https://github.com/medic/cht-conf/tree/596_semver_fix)).

Thank you! 😊

**Comment by 1yuv** [comment] 2024-01-10 21:42
Hi @tatilepizs , 

You can see the failure in current version in these deployments on [gandaki](https://github.com/medic/config-moh-nepal/commit/950f48a20c9b9256b0dbab582b64e78ffb7bdc4e/checks) and [echis ke](https://github.com/moh-kenya/config-echis-2.0/actions/runs/7475788184/job/20344693143#step:7:366). 

Also, I've attached here the video of failure and pass. 

**Failing in 3.21.1**

https://github.com/medic/cht-conf/assets/6102813/b020020b-0722-4a39-8fa1-f83992404cef

**Fix:**


https://github.com/medic/cht-conf/assets/6102813/0a3b24ff-d080-4ed2-bb56-7deb7b0a9471

**Closed** 2024-01-10 23:03 UTC
Labels: Type: Bug
