### ISSUE TITLE
compile-app-settings with --debug flag does not ignore eslint errors

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-conf#533] opened 2023-01-26 16:23 UTC
**Describe the bug**
The `compile-app-settings -- --debug` flag 

**To Reproduce**
1. Remove a semicolon from tasks.js
2. Run `compile-app-settings -- --debug`

**Expected behavior**
Eslint error should be skipped
https://github.com/medic/cht-conf/blob/main/release-notes.md#debug-mode-for-compile-app-settings

**Environment**
- cht-conf version: latest

**Additional context**
Regression from https://github.com/medic/cht-conf/issues/414

**Comment by kennsippell** [comment] 2023-02-13 18:36
@garethbowen @dianabarsan Now that this has passed code review what do I do?

**Comment by garethbowen** [comment] 2023-02-14 04:33
@kennsippell The process is to send it for AT. Add it to the Product Team Activities project, and move it to the Ready for AT column. Add a comment to this issue with AT instructions (in this case, this isn't necessary because you've added reproduction steps above!).

When it passes AT, remember to be careful when merging to use the specific [commit format](https://github.com/medic/cht-conf#commit-format) so it gets released in the CD process.

**Comment by kennsippell** [comment] 2023-02-14 08:58
Ready for AT on `debug-eslint-warning`

**Closed** 2023-03-18 21:01 UTC
Labels: Type: Bug, released
