### ISSUE TITLE
cht upload-docs fails for databases other than medic.

### ISSUE THREAD

**Issue by yrimal** [medic/cht-conf#464] opened 2022-01-30 15:10 UTC
Certain cht actions fail for databases other than `medic`. One of which is
```shell
cht upload-docs
```
**Steps to replicate:**
- Create instance that doesn't use default `medic` database but something else. 
- Try to run converted docs, using 
```shell
cht --url=https://user:password@instance_url:port/chis2 upload-docs
```

Following error will be displayed:
 ```
ERROR Failed to get a response from https://user:****@localhost:5988/chis2medic/. 
Maybe you entered the wrong URL, wrong port or the instance is not started. Please check and try again. 
```

**Comment by dianabarsan** [comment] 2022-01-31 05:43
Can you please try omitting the `chis2` suffix and just use `https://user:password@instance_url:port/` ?

**Comment by dianabarsan** [comment] 2022-01-31 05:45
If the above works, we should consider documenting this.

**Comment by yrimal** [comment] 2022-01-31 15:47
>I'd also be curious what the use case is for this so I can appreciate how many people this bug affects.

Hi @mrjones-plip , I can not speak of all, but I believe internal app developers who need to work on multiple instances frequently follow this practice.

**Comment by yrimal** [comment] 2022-01-31 15:56
Hi @dianabarsan 🥇  , Thank's for the workaround tips. 
>Can you please try omitting the chis2 suffix and just use https://user:password@instance_url:port/ ?
This actually worked !

**Comment by mrjones-plip** [comment] 2022-01-31 18:28
> I can not speak of all, but I believe internal app developers who need to work on multiple instances frequently follow this practice.

Thanks @yrimal - I'll follow up with App Services to gather up this info.  If there's anything relevant, I'll be sure to share it back here.

**Comment by mrjones-plip** [comment] 2022-02-03 19:29
@dianabarsan  and @yrimal - is a sufficient fix to just add a note in the "[Specifying the server to configure](https://github.com/medic/cht-conf/#specifying-the-server-to-configure)" section about different database names or do we think there's defensive code to add to `cht-conf`?

**Comment by dianabarsan** [comment] 2022-02-04 09:01
As far as I can tell, throughout the readme, all example URLs **don't** include the database name (be it medic or something else). 
The issue above is caused by using the database name in the passed URL. 

Support for different database names was never added to cht-conf because we have a workaround in API, where it redirects all requests to "medic" database to the correct database.

**Comment by mrjones-plip** [comment] 2022-02-04 16:49
Ah - so the defensive code is already there in the API - awesome!! 

A caveat in the `cht-conf` docs to call out something like,

> Support for database names other than `medic` is achieved via implicit downstream checks in the CHT. This means do **not** specify the database name when using the `--url` flag - the CHT API will find the correct database.

sound good?

**Comment by dianabarsan** [comment] 2022-02-07 10:51
I'm not sure we should even mention the part about the database name not being medic, and could just say to not include the db name in the URL.

**Comment by garethbowen** [comment] 2022-02-23 23:01
@mrjones-plip Is the linked PR sufficient to close this issue, or is there more to be done here?

**Comment by mrjones-plip** [comment] 2022-02-23 23:21
I'll risk closing it to move us forward, trusting that the watchers on this ticket will call me out if I'm wrong :pray:

**Closed by mrjones-plip** 2022-02-23 23:21 UTC
Labels: Type: Bug
