### ISSUE TITLE
`ERROR: Failed to update xform: { .. }` logs in API when uploading configs with medic-conf

### ISSUE THREAD

**Issue by mrsarm** [medic/cht-conf#402] opened 2021-04-26 16:49 UTC
**Describe the bug**
I'm not sure if the bug is caused by medic-conf or the API, but because it is related with config being loaded by medic-conf, the issue is reported here instead of the CHT.

When pushing configurations with `medic-conf --local` to the CHT, I see a bunch of errors like this in the API logs:

```diff
...
2021-04-26 16:16:35 INFO: Detected form change - generating attachments 
RES 66e419db-6566-489b-a969-e55bf25dc9b1 ::ffff:127.0.0.1 admin DELETE /medic/form%3Apregnancy?rev=5-105ff55551020cab5bc5b7dfbd80af86 HTTP/1.1 200 77 360.882 ms
RES e79d87e7-5f08-4646-be0b-5a6fc5cbdccb ::ffff:127.0.0.1 admin DELETE /medic/form%3Apnc_danger_sign_follow_up_baby?rev=5-2697a3855cf9b6b849de722df4f2c7a3 HTTP/1.1 200 98 364.092 ms
- 2021-04-26 16:16:35 ERROR: Failed to update xform: {
  error: 'not_found',
  reason: 'deleted',
  status: 404,
  name: 'not_found',
  message: 'deleted',
  docId: 'form%3Aundo_death_report'
} 
- 2021-04-26 16:16:35 ERROR: Failed to update xform: {
  error: 'not_found',
  reason: 'deleted',
  status: 404,
  name: 'not_found',
  message: 'deleted',
  docId: 'form%3Acontact%3Ahealth_center%3Acreate'
} 
- 2021-04-26 16:16:35 ERROR: Failed to update xform: {
  error: 'not_found',
  reason: 'deleted',
  status: 404,
  name: 'not_found',
  message: 'deleted',
  docId: 'form%3Acontact%3Aperson%3Acreate'
} 
2021-04-26 16:16:35 INFO: Detected form change - generating attachments 
2021-04-26 16:16:35 INFO: Detected form change - generating attachments 
...
```

It happens either when you push the configuration for the first time or any time later. I could reproduce the error using the configs under the [config/default](https://github.com/medic/cht-core/tree/master/config/default) folder and other configs I used to test the bug, like the [config/standard](https://github.com/medic/cht-core/tree/master/config/standard)  config, or the [educational_modules](https://github.com/medic/config-covid/tree/master/educational_modules).

**To Reproduce**
1. Launch any of the latest or master version of the CHT
2. Go to the `config/default` folder within the console and execute `medic-conf --local`
3. Check the API logs to see the errors.

**Expected behavior**
The configuration seems to be uploaded without problems, so we shouldn't see errors in the API logs. Although I cannot confirm that all the configurations were uploaded as expected so maybe a real error is happening, in that case we should also improve the log output to make the error more clear.

**Environment**
- Instance: tested only with local instances
- Client platform: Linux
- medic-conf version: tested with 3.4.1 and master (3.5.0), not sure if the error also happens in older versions
- cht-core version: tested with 3.10.0 and master (3.11.0)

**Additional context**
The error happens in a particular section in the API that maybe is expected to happen, but in that case we shouldn't log the error like that, making the process to look like failed when is not.

**Comment by dianabarsan** [comment] 2022-12-09 10:52
I think this issue was caused by the forms being deleted and then reuploaded, and API trying to process those deletes. 
I believe this has been fixed by https://github.com/medic/cht-core/issues/7608 .

**Comment by tatilepizs** [comment] 2023-01-23 16:27
Hi @dianabarsan, is there something extra that we should test about this ticket? because I see that the https://github.com/medic/cht-core/issues/7608 was already tested by @ngaruko and was already merged, and the issue looks pretty similar.

**Comment by dianabarsan** [comment] 2023-01-23 16:36
If you're happy with just closing this, since it's similar, then I'm fine with it. 
The alternative is to go through the steps described above and check whether API still logs those errors.

**Comment by tatilepizs** [comment] 2023-01-23 18:13
Moved to `done` since there is nothing to merge.

**Comment by dianabarsan** [comment] 2023-01-23 18:45
Thanks @tatilepizs . I'll close it!

**Closed by dianabarsan** 2023-01-23 18:45 UTC
Labels: Type: Bug
